#!/usr/bin/env python3
"""Generate a frontend reference intelligence report from downloaded HTML references."""

from __future__ import annotations

import argparse
import collections
import pathlib
import re
from typing import Iterable

TOKEN_PATTERNS = {
    "motion": re.compile(r"\b(animate-|transition|duration-|ease-|@keyframes|hover:|active:|group-hover)"),
    "layout": re.compile(r"\b(grid|flex|container|columns-|col-span-|gap-|px-|py-|mx-|my-|w-|h-|min-h-|max-w-)"),
    "visual": re.compile(r"\b(bg-|gradient|shadow|blur|backdrop|border|rounded|opacity|mask-|mix-blend|glass)"),
    "typography": re.compile(r"\b(font-|text-|tracking-|leading-|uppercase|lowercase|italic|antialiased)"),
    "interaction": re.compile(r"\b(hover:|focus:|focus-within|cursor-|pointer-events|snap-|scroll-|group)"),
}

SPECIAL_TECH_PATTERNS = {
    "tailwind": re.compile(r"tailwind\.config|cdn\.tailwindcss\.com", re.IGNORECASE),
    "lenis_or_locomotive": re.compile(r"lenis|locomotive", re.IGNORECASE),
    "iframe_usage": re.compile(r"<iframe|spline", re.IGNORECASE),
    "icon_system": re.compile(r"lucide|iconify|data-lucide", re.IGNORECASE),
}

CLASS_ATTR_RE = re.compile(r'class\s*=\s*"([^"]+)"', re.IGNORECASE)


def find_html_files(base: pathlib.Path) -> list[pathlib.Path]:
    return sorted(base.glob("referencias/*/index.html"))


def tokenize_classes(html_text: str) -> list[str]:
    classes: list[str] = []
    for cls_blob in CLASS_ATTR_RE.findall(html_text):
        classes.extend([c for c in cls_blob.split() if c])
    return classes


def pattern_hits(tokens: Iterable[str], pattern: re.Pattern[str]) -> int:
    return sum(1 for t in tokens if pattern.search(t))


def infer_style_signature(name: str, html_text: str, tokens: list[str]) -> str:
    lower = name.lower()
    flags = []
    if "dashboard" in lower:
        flags.append("dashboard-density")
    if "glass" in lower or "glass" in html_text.lower():
        flags.append("glassmorphism")
    if "animation" in lower or pattern_hits(tokens, TOKEN_PATTERNS["motion"]) > 25:
        flags.append("motion-heavy")
    if "capture" in lower or "pagina" in lower:
        flags.append("lead-capture")
    if "portfolio" in lower:
        flags.append("editorial-portfolio")
    if "instagram" in lower:
        flags.append("story-slider")
    if not flags:
        flags.append("general-web")
    return ", ".join(flags)


def build_report(base: pathlib.Path, output: pathlib.Path) -> None:
    files = find_html_files(base)
    if not files:
        raise SystemExit(f"No reference HTML files found under: {base}")

    global_counter: collections.Counter[str] = collections.Counter()
    rows: list[str] = []

    for html_file in files:
        text = html_file.read_text(encoding="utf-8", errors="ignore")
        tokens = tokenize_classes(text)
        global_counter.update(tokens)
        sample = ", ".join([c for c, _ in collections.Counter(tokens).most_common(12)])

        stats = {k: pattern_hits(tokens, p) for k, p in TOKEN_PATTERNS.items()}
        tech_flags = [k for k, p in SPECIAL_TECH_PATTERNS.items() if p.search(text)]
        style_sig = infer_style_signature(html_file.parent.name, text, tokens)

        rows.append(
            f"| `{html_file.parent.name}` | {len(tokens)} | {stats['motion']} | {stats['layout']} | {stats['visual']} | {stats['typography']} | {stats['interaction']} | {', '.join(tech_flags) or '-'} | {style_sig} | {sample} |"
        )

    top_global = "\n".join([f"- `{cls}` ({count})" for cls, count in global_counter.most_common(40)])

    md = f"""# Vibe Design Extraction Report

Source base: `{base}`
Generated by: `~/.claude/tools/vibe_pack_builder.py`

## Per Reference Breakdown
| Reference | Class Tokens | Motion | Layout | Visual | Typography | Interaction | Tech Flags | Style Signature | Frequent Classes |
|---|---:|---:|---:|---:|---:|---:|---|---|---|
{chr(10).join(rows)}

## Global Most Reused Utility Classes
{top_global}

## Practical Interpretation
- References are heavily utility-class driven and optimized for fast composition.
- Motion and interaction are core identity layers, not decorative extras.
- Visual depth repeatedly uses gradients, blur, border overlays and soft shadows.
- Layout relies on reusable primitives (`grid`, `flex`, spacing scale) with strong responsive behavior.
"""
    output.write_text(md, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate frontend reference intelligence report")
    parser.add_argument("--refs", required=True, help="Path containing referencias/*/index.html")
    parser.add_argument("--out", required=True, help="Output markdown path")
    args = parser.parse_args()

    refs = pathlib.Path(args.refs).expanduser().resolve()
    out = pathlib.Path(args.out).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    build_report(refs, out)
    print(str(out))


if __name__ == "__main__":
    main()
